[package]
name = "rustyblue"
version = "0.1.0"
edition = "2021"
resolver ="2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
patricia_tree = "0.3.1"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.64"
